pipeline {
   agent any
   tools {
        maven 'M3'
        jdk 'jdk1.8'
    }
   stages {
      stage('Build') {
         steps {
            // Run the maven build
            bat(/"mvn" -f streams\/pom.xml -Dmaven.test.failure.ignore clean package/)
         }
      }
      stage('Results') {
         steps {
            junit '**/target/surefire-reports/TEST-*.xml'
            archiveArtifacts 'streams/target/*.jar'
         }
      }
   }
}
