pipeline {
   agent any
   tools {
        maven 'M3'
        jdk 'jdk1.8'
    }
   stages {
      stage ('Initialize') {
            steps {
                sh echo "PATH = ${PATH}"
                sh echo "M2_HOME = ${M2_HOME}"
            }
        }
      stage('Preparation') { // for display purposes
         steps {
            // Get some code from a GitHub repository
            git 'https://github.com/patanjalic/java8concepts.git'
         }
      }
      stage('Build') {
         steps {
            // Run the maven build
            if (isUnix()) {
               sh "'mvn' -Dmaven.test.failure.ignore clean package"
            } else {
               bat(/"mvn" -f streams\/pom.xml -Dmaven.test.failure.ignore clean package/)
            }
         }
      }
      stage('Results') {
         steps {
            junit '**/target/surefire-reports/TEST-*.xml'
            archiveArtifacts 'streams/target/*.jar'
         }
      }
   }
}
