pipeline {
   agent any
   def mvnHome
   stages {
      stage('Preparation') { // for display purposes
         // Get some code from a GitHub repository
         git 'https://github.com/patanjalic/java8concepts.git'
         // Get the Maven tool.
         // ** NOTE: This 'M3' Maven tool must be configured
         // **       in the global configuration.           
         mvnHome = tool 'M3'
      }
      stage('Build') {
         // Run the maven build
         if (isUnix()) {
            sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
         } else {
            bat(/"${mvnHome}\bin\mvn" -f streams\/pom.xml -Dmaven.test.failure.ignore clean package/)
         }
      }
      stage('Results') {
         junit '**/target/surefire-reports/TEST-*.xml'
         archiveArtifacts 'streams/target/*.jar'
      }
   }
}
